### ISSUE TITLE
Inaccurate GWP reporting for steel framing elements

### ISSUE THREAD

**Issue by michaelhoehn** [BHoM/CarbonQueryDatabase_Toolkit#39]
#### Description:

I'm not seeing matching GWP values. Most likely this is occurring within the convert as there are several "GWP" properties within any API request return. 

![image](https://user-images.githubusercontent.com/54593392/82912048-97af7780-9f3a-11ea-93f3-6ade307c4b37.png)

#### Expected behaviour:

Assuming we should be returning conservative estimates as with concrete materials.

**Comment by enarhi** [comment]
These values are per kg, not per lb, and are equivalent to the EC3 values shown per kg rather than per lb for the average value.

**Comment by michaelhoehn** [comment]
Thanks @enarhi for the clarification. Will do some additional spot checks as discussed for other materials and address as needed in future issues.
