### ISSUE TITLE
CQDConfig component showing an error

### ISSUE THREAD

**Issue by enarhi** [BHoM/CarbonQueryDatabase_Toolkit#62]
#### Description:
This error shows up when opening a script with the CQDCOnfig component in it. Everything still functions as expected, so the only issue here is the cause of the error showing up in the first place.

![image](https://user-images.githubusercontent.com/6752345/101943853-b147a200-3ba0-11eb-81ed-8575a6d73d98.png)

**Comment by FraserGreenroyd** [comment]
@enarhi try the PR on the BHoM_Adapter which looks like it solves this, this has been captured on Versioning_Toolkit and is not an issue for @michaelhoehn to resolve on this toolkit.

**Comment by FraserGreenroyd** [comment]
@enarhi might need to build something from Versioning Toolkit to have it all working correctly.

**Comment by FraserGreenroyd** [comment]
For what it's worth, @JohannaOlin1 found a similar problem with the XML Config.

**Comment by enarhi** [comment]
Confirming this is fixed by changes elsewhere, closing.
