### ISSUE TITLE
EC3 pull all EPDs with certain search criteria

### ISSUE THREAD

**Issue by ajensen19** [BHoM/CarbonQueryDatabase_Toolkit#7]
#### Description: 

Seems the current pass at the Carbon Query Database pull adapter method uses a “Count” field which limits the number of EPDs that are pulled to a specified number, limiting our ability to summarize across a set of EPDs. For example, if we want to be able to use the average of all Colorado-based EPDs for 2000psi concrete, we can't be sure we are getting all the relevant EPDs counted in the average if we are only pulling ten. I'm wondering how we envision this working in the future as we get beyond industry-wide EPDs!

**Comment by enarhi** [comment]
closing this as is relates to #6
