### ISSUE TITLE
CQD Does not work in Grasshopper UI 

### ISSUE THREAD

**Issue by michaelhoehn** [BHoM/CarbonQueryDatabase_Toolkit#95]
#### Description:

Likely a Netstandard upgrade issue @FraserGreenroyd? Could use your help on this one. 

#### Steps to reproduce:

Using the sample file along with the current beta release 5.1, try to pull any object from the CQD database. This will result in an empty pull no matter the request in the Grasshopper UI. The switch to the Excel file and toggle the pull to True. This will pull EPD objects as expected. 

#### Expected behaviour:

Pull functionality should work within Grasshopper as seen in the Excel test file. 

#### Test file(s):

[Grasshopper test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/CarbonQueryDatabase_Toolkit/CarbonQueryDatabase_Toolkit%20%2395-Not%20working%20in%20grasshopper.gh?csf=1&web=1&e=XBDEFP)

[Excel test file](https://burohappold.sharepoint.com/:x:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/CarbonQueryDatabase_Toolkit/CarbonQueryDatabase_Toolkit%20%2395.xlsx?d=w13b04478f8f144acb7dddc5968b6aa7f&csf=1&web=1&e=CdRCR6)

**Comment by FraserGreenroyd** [comment]
@michaelhoehn I'd need some steps to reproduce to even begin working out what you mean here. Have you got a description/example of how CDQ doesn't work in the Grasshopper UI?

**Comment by michaelhoehn** [comment]
Working on it. I didn't expect you to answer while you were OOO 😛

**Comment by FraserGreenroyd** [comment]
You tagged me directly, it woke me from my slumber 😉

**Comment by enarhi** [comment]
This was just due to the Grasshopper script missing the required TypeRequest (EnvironmentalProductDeclaration) on the Pull. With the Type Request provided it works as expected.

**Comment by michaelhoehn** [comment]
Leaving a note after some testing with @enarhi 
Seems it's been a while since last using the toolkit sample I had a lapse in memory regarding the need to provide a TypeRequest on Pull even though I specified the Type in the ActionConfig. I recall moving the type to the action config for simplicity a while back, but neglected to alter or enhance the adapter user experience with the changes through messaging (warning or otherwise). 

Here's a link to a new issue requesting better messaging which should clear up this specific confusion. 

https://github.com/BHoM/CarbonQueryDatabase_Toolkit/issues/96
